language: node_js

os:
  - linux
  - osx
node_js:
  - "8.9" # vscode >= 1.26.0
  - "7.9" # vscode >= 1.16.0 < 1.26.0
  - "7.4" # vscode >= 1.12.0 < 1.16.0
  - "6.5" # vscode >= 1.8.0 < 1.12.0

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)